
import React, { useState, useMemo } from 'react';
import { SalarySlip, User, Teacher } from '../types';
import { MOCK_SALARY_SLIPS } from '../constants';
import { FinanceIcon, Download, CheckCircle, FileText, Search, UserCheck, Activity, X } from './Icons';

interface PayrollProps {
  user: User;
  teachers: Teacher[];
}

export const Payroll = ({ user, teachers }: PayrollProps) => {
  const isAdmin = user.role === 'Admin' || user.role === 'PlatformAdmin';
  const [selectedTeacherId, setSelectedTeacherId] = useState<string | null>(null);
  const [searchTerm, setSearchTerm] = useState('');

  // If Admin, show staff selection. If Teacher, show their own.
  const targetTeacherId = isAdmin ? selectedTeacherId : user.id;
  const slips = MOCK_SALARY_SLIPS.filter(s => s.teacherId === (targetTeacherId || 'teacher'));
  
  const filteredTeachers = useMemo(() => {
    return teachers.filter(t => t.name.toLowerCase().includes(searchTerm.toLowerCase()) || t.id.toLowerCase().includes(searchTerm.toLowerCase()));
  }, [teachers, searchTerm]);

  const handleDownloadSlip = (slip: SalarySlip) => {
    const teacherName = teachers.find(t => t.id === slip.teacherId)?.name || user.name;
    const win = window.open('', '', 'height=700,width=800');
    if (win) {
      win.document.write(`
        <html><head><title>Salary Slip - ${slip.month}</title>
        <style>
          body{font-family:sans-serif;padding:40px;color:#333;}
          .header{text-align:center;border-bottom:2px solid #000;padding-bottom:20px;}
          .details{margin:30px 0;line-height:2;}
          table{width:100%;border-collapse:collapse;}
          th,td{padding:12px;border:1px solid #ddd;text-align:left;}
          .total{background:#f1f5f9;font-weight:black;}
        </style>
        </head><body>
          <div class="header"><h1>QODECAMPUS ERP</h1><h2>OFFICIAL SALARY DISBURSEMENT</h2></div>
          <div class="details">
            <p><strong>Employee:</strong> ${teacherName}</p>
            <p><strong>Reference ID:</strong> ${slip.id}</p>
            <p><strong>Cycle:</strong> ${slip.month} ${slip.year}</p>
            <table>
              <tr><td>Core Basic Pay</td><td>₹${slip.basic.toLocaleString()}</td></tr>
              <tr><td>HRA (House Rent)</td><td>₹${slip.hra.toLocaleString()}</td></tr>
              <tr><td>Institutional Allowance</td><td>₹${slip.allowance.toLocaleString()}</td></tr>
              <tr><td>Tax & Statutory Deductions</td><td style="color:red">-(₹${slip.deductions.toLocaleString()})</td></tr>
              <tr class="total"><td><strong>Net Credited Amount</strong></td><td><strong>₹${slip.netAmount.toLocaleString()}</strong></td></tr>
            </table>
          </div>
          <p style="text-align:right;margin-top:50px;">Digital Validation: 0x932...AF</p>
          <script>window.print();</script>
        </body></html>
      `);
      win.document.close();
    }
  };

  const totalMonthlyOutflow = useMemo(() => {
     return slips.reduce((acc, s) => acc + s.netAmount, 0);
  }, [slips]);

  return (
    <div className="space-y-8 animate-in pb-20">
      {/* Header Stat Card */}
      <div className="bg-slate-950 p-8 lg:p-14 rounded-[3rem] lg:rounded-[4rem] text-white relative overflow-hidden shadow-ultra group">
         <div className="absolute top-0 right-0 w-96 h-96 bg-indigo-600/10 rounded-full blur-[100px] -mr-32 -mt-32 pointer-events-none floating-ui"></div>
         <div className="relative z-10 flex flex-col lg:flex-row justify-between items-start lg:items-center gap-10">
            <div className="max-w-2xl">
               <div className="flex items-center gap-3 text-indigo-400 text-[10px] font-black uppercase tracking-[0.5em] mb-6">
                 <span className="w-2 h-2 rounded-full bg-indigo-500 shadow-glow-indigo animate-pulse"></span>
                 Fiscal Ledger
               </div>
               <h2 className="text-4xl lg:text-6xl font-black tracking-tighter leading-tight">
                 {isAdmin ? 'Staff Remuneration Matrix' : 'Earning Repository'}
               </h2>
               <p className="text-slate-400 text-sm lg:text-lg font-medium mt-4 opacity-80 leading-relaxed">
                 {isAdmin 
                    ? "Institutional transparency override enabled. Audit salary disbursements across the entire faculty ecosystem." 
                    : "Access your historical earnings and synchronized salary artifacts generated by the Matrix Engine."}
               </p>
            </div>
            <div className="bg-white/5 backdrop-blur-3xl p-8 lg:p-10 rounded-[3rem] border border-white/10 text-center min-w-[280px] shadow-ultra group hover:bg-white/10 transition-all border-indigo-500/20">
               <p className="text-[10px] font-black uppercase text-indigo-300 mb-3 tracking-[0.3em] opacity-80">
                 {isAdmin ? 'Monthly Outflow' : 'Last Net Credit'}
               </p>
               <p className="text-5xl lg:text-7xl font-black tracking-tighter">₹{(isAdmin ? totalMonthlyOutflow : slips[0]?.netAmount || 0).toLocaleString()}</p>
               <p className="text-[9px] font-bold text-slate-500 uppercase mt-4 tracking-widest">Digital Settlement: COMPLETED</p>
            </div>
         </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-8">
        {/* Admin Staff Selector */}
        {isAdmin && (
          <div className="xl:col-span-1 bg-white rounded-[3.5rem] shadow-premium border border-slate-50 overflow-hidden flex flex-col h-[700px] card-glow-indigo">
             <div className="p-8 border-b border-slate-50 bg-slate-50/30">
                <div className="flex justify-between items-center mb-6">
                   <h3 className="font-black text-slate-800 text-xl tracking-tight">Faculty Directory</h3>
                   <Activity className="w-5 h-5 text-indigo-500 animate-pulse" />
                </div>
                <div className="relative group">
                   <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-300 group-focus-within:text-indigo-500 transition-colors w-4 h-4" />
                   <input 
                     type="text" 
                     placeholder="Search faculty..." 
                     className="w-full pl-10 pr-4 py-3 rounded-2xl bg-white border-slate-100 focus:bg-white focus:ring-4 focus:ring-indigo-50 transition-all outline-none font-bold text-xs shadow-inner-soft"
                     value={searchTerm}
                     onChange={e => setSearchTerm(e.target.value)}
                   />
                </div>
             </div>
             <div className="flex-1 overflow-y-auto p-6 space-y-3 custom-scrollbar">
                {filteredTeachers.map(teacher => (
                  <div 
                    key={teacher.id} 
                    onClick={() => setSelectedTeacherId(teacher.id)}
                    className={`p-6 rounded-[2rem] border transition-all cursor-pointer group active-scale ${
                      selectedTeacherId === teacher.id 
                      ? 'bg-indigo-600 text-white border-indigo-600 shadow-xl shadow-indigo-100' 
                      : 'bg-white border-slate-100 hover:bg-slate-50 hover:border-indigo-100'
                    }`}
                  >
                    <div className="flex justify-between items-center">
                       <div className="flex items-center gap-4">
                          <div className={`w-12 h-12 rounded-2xl flex items-center justify-center text-xl font-black uppercase transition-colors ${
                            selectedTeacherId === teacher.id ? 'bg-white/20' : 'bg-slate-50 text-slate-300'
                          }`}>
                             {teacher.name[0]}
                          </div>
                          <div>
                             <p className="font-black text-sm tracking-tight">{teacher.name}</p>
                             <p className={`text-[10px] font-bold uppercase tracking-widest ${selectedTeacherId === teacher.id ? 'text-indigo-100' : 'text-slate-400'}`}>
                               {teacher.subject}
                             </p>
                          </div>
                       </div>
                       {selectedTeacherId === teacher.id && <CheckCircle className="w-5 h-5" />}
                    </div>
                  </div>
                ))}
             </div>
          </div>
        )}

        {/* Ledger Grid */}
        <div className={`${isAdmin ? 'xl:col-span-2' : 'xl:col-span-3'} space-y-8`}>
          {isAdmin && !selectedTeacherId ? (
            <div className="h-[700px] flex flex-col items-center justify-center text-center p-10 bg-slate-50/50 rounded-[4rem] border border-dashed border-slate-200">
               <div className="w-24 h-24 bg-white rounded-[3rem] shadow-premium flex items-center justify-center mb-8">
                  <UserCheck className="w-12 h-12 text-slate-200" />
               </div>
               <h3 className="text-2xl font-black text-slate-800">Select Staff Instance</h3>
               <p className="text-slate-400 text-sm font-medium mt-2 max-w-xs">Please choose a faculty member from the directory to audit their fiscal artifacts.</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-8">
              {slips.map(slip => (
                <div key={slip.id} className="bg-white p-8 lg:p-10 rounded-[3.5rem] shadow-premium border border-slate-100 flex flex-col group hover-scale active-scale card-glow-emerald">
                   <div className="flex justify-between items-start mb-10">
                      <div className="w-16 h-16 bg-emerald-50 text-emerald-600 rounded-[1.75rem] flex items-center justify-center shadow-inner group-hover:rotate-6 transition-transform">
                        <CheckCircle className="w-8 h-8" />
                      </div>
                      <div className="text-right">
                         <span className="text-[10px] font-black uppercase bg-slate-50 px-4 py-2 rounded-full text-slate-400 tracking-[0.2em]">{slip.month} {slip.year}</span>
                         <p className="text-[9px] font-black text-indigo-500 uppercase mt-3 tracking-widest">{slip.id}</p>
                      </div>
                   </div>
                   <h3 className="text-2xl font-black text-slate-800 mb-2">Institutional Credit</h3>
                   <p className="text-slate-400 text-xs font-bold uppercase tracking-widest mb-10">Status: <span className="text-emerald-500">{slip.status}</span></p>
                   
                   <div className="mt-auto space-y-6 pt-8 border-t border-slate-50">
                      <div className="flex justify-between items-center">
                         <span className="text-slate-400 font-black uppercase text-[10px] tracking-widest">Net Disbursed</span>
                         <span className="text-3xl font-black text-slate-900 tracking-tighter">₹{slip.netAmount.toLocaleString()}</span>
                      </div>
                      <button 
                         onClick={() => handleDownloadSlip(slip)}
                         className="w-full py-5 bg-slate-50 group-hover:bg-indigo-600 group-hover:text-white text-slate-600 rounded-3xl font-black text-[10px] uppercase tracking-[0.3em] transition-all flex items-center justify-center gap-3 active-scale btn-vibrant"
                      >
                         <FileText className="w-5 h-5" /> Export PDF Slip
                      </button>
                   </div>
                </div>
              ))}
              {slips.length === 0 && (
                <div className="col-span-full py-40 text-center opacity-20">
                   <FinanceIcon className="w-20 h-20 mx-auto mb-6 text-slate-300" />
                   <p className="font-black uppercase tracking-[0.5em] text-xs">No ledger entries detected</p>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
